from app.db.models.user import User
from app.db.models.course import Course
from app.db.models.section import Section
from app.db.models.enrollment import Enrollment
from app.db.models.room import Room
from app.db.models.scheduled_meeting import ScheduledMeeting
from app.db.models.course_prerequisite import CoursePrerequisite
from app.db.models.course_eligibility import CourseEligibility
from app.db.models.registration_setting import RegistrationSetting